baseURL = "https://jbelborja17.github.io/profile/"
languageCode = "en"
title = "Javier Bel"
theme = "PaperMod"
enableRobotsTXT = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "experience"
    name = "Experience"
    url = "/experience/"
    weight = 20

[params]
  mainSections = []
  defaultTheme = "light"
  disableThemeToggle = false
  showReadingTime = false
  showPostNavLinks = false
  showCodeCopyButtons = true


