baseURL = "https://jbelborja17.github.io/profile/"
languageCode = "es"
title = "Mi perfil profesional"
theme = "PaperMod"
enableRobotsTXT = true

[menu]
  [[menu.main]]
    identifier = "experience"
    name = "Experience"
    url = "/experience/"
    weight = 20

